name: redeploy-portainer-stack
description: Redeploy a Portainer CE Web editor stack from GitHub Actions CI
author: nonk123

inputs:
  url:
    description: Your Portainer CE instance public URL, such as `https://portainer.example.org:9443`.
    required: true

  username:
    description: Username to log into your Portainer CE instance.
    required: true

  password:
    description: Password to log into your Portainer CE instance.
    required: true

  stack_id:
    description: Portainer stack ID. See the action's README for where to get it from.
    required: true

  endpoint_id:
    description: Portainer environment ID. See the action's README for where to get it from.
    required: true

runs:
  using: composite
  steps:
    - name: Log into the Portainer instance
      shell: bash
      run: |
        set -e

        JWT_TOKEN=$(curl -sf -X POST \
          -H "Content-Type: application/json" \
          -d '{"username":"${{ inputs.username }}","password":"${{ inputs.password }}"}' \
          "${{ inputs.url }}/api/auth" | jq -r '.jwt')
        echo "::add-mask::$JWT_TOKEN"
        echo "JWT_TOKEN=$JWT_TOKEN" >> $GITHUB_ENV

    - name: Check stack access permissions
      shell: bash
      run: |
        code=$(curl -s -o /dev/null -w "%{http_code}" -H "Authorization: Bearer $JWT_TOKEN" "${{ inputs.url }}/api/stacks/${{ inputs.stack_id }}")

        if [[ "$code" != 200 ]]; then
          echo "::error::Failed to access Portainer stack: HTTP code $code"
          exit 1
        fi

    - name: Fetch stack environment variables
      shell: bash
      run: |
        set -e

        ENV_VALUE=$(curl -sf -H "Authorization: Bearer $JWT_TOKEN" \
          "${{ inputs.url }}/api/stacks/${{ inputs.stack_id }}" | jq -c .Env)
        echo "::add-mask::$ENV_VALUE"
        echo "ENV_VALUE=$ENV_VALUE" >> $GITHUB_ENV

    - name: Fetch stack YAML definition
      shell: bash
      run: |
        set -e

        STACK_CONTENT=$(curl -sf -H "Authorization: Bearer $JWT_TOKEN" \
          "${{ inputs.url }}/api/stacks/${{ inputs.stack_id }}/file" | jq -c .StackFileContent)
        echo "::add-mask::$STACK_CONTENT"
        echo "STACK_CONTENT=$STACK_CONTENT" >> $GITHUB_ENV

    - name: Force Portainer CE stack update
      shell: bash
      run: |
        set -e

        curl -sf -X PUT -o /dev/null \
          -H "Authorization: Bearer $JWT_TOKEN" \
          -H "Content-Type: application/json" \
          -d "{\"stackFileContent\":$STACK_CONTENT,\"env\":$ENV_VALUE,\"prune\": true,\"pullImage\": true}" \
          "${{ inputs.url }}/api/stacks/${{ inputs.stack_id }}?endpointId=${{ inputs.endpoint_id }}"
