name: redeploy-portainer-stack
description: Redeploy a Portainer CE stack from GitHub Actions CI
author: nonk123

inputs:
  url:
    description: Your Portainer CE instance public URL, such as `https://portainer.example.org:9443`.
    required: true

  username:
    description: Username to log into your Portainer CE instance.
    required: true

  password:
    description: Password to log into your Portainer CE instance.
    required: true

  stack_id:
    description: Portainer stack ID. See project's README for where to get it from.
    required: true

  endpoint_id:
    description: Portainer environment ID. See project's README for where to get it from.
    required: true

runs:
  using: composite
  steps:
    - name: Log into the Portainer instance
      shell: bash
      run: |
        JWT_TOKEN=$(curl -s -X POST \
          -H "Content-Type: application/json" \
          -d '{"username":"${{ inputs.username }}","password":"${{ inputs.password }}"}' \
          "${{ inputs.url }}/api/auth" | jq -r '.jwt')
        echo "::add-mask::$JWT_TOKEN"
        echo JWT_TOKEN=$JWT_TOKEN >> $GITHUB_ENV

    - name: Fetch stack definition
      shell: bash
      run: |
        STACK_CONTENT=$(curl -s -H "Authorization: Bearer $JWT_TOKEN" \
          "${{ inputs.url }}/api/stacks/${{ inputs.stack_id }}/file" | jq -r .stackFileContent)

        echo "$STACK_CONTENT" | sed 's/^/::add-mask::/'

        echo "STACK_CONTENT<<EOF" >> $GITHUB_ENV
        echo "$STACK_CONTENT" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV

    - name: Force Portainer CE stack update
      shell: bash
      run: |
        curl -s -X PUT \
          -H "Authorization: Bearer $JWT_TOKEN" \
          -H "Content-Type: application/json" \
          -d "{\"stackFileContent\":$(echo -n "$STACK_CONTENT" | jq -R -s .),\"env\":[],\"prune\": true,\"pullImage\": true}" \
          "${{ inputs.url }}/api/stacks/${{ inputs.stack_id }}?endpointId=${{ inputs.endpoint_id }}"
